# Generated by Django 4.2 on 2023-11-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandiose', '0002_post_liked_by_post_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_on',
        ),
    ]
