# Generated by Django 4.2 on 2023-11-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandiose', '0004_posts_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
