# Generated by Django 4.2 on 2023-11-27 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grandiose', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
